[project]
name = "10-04-24"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "baml-py>=0.58.0",
    "ipykernel>=6.29.5",
    "openai>=1.51.0",
    "python-dotenv>=1.0.1",
]
