###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import Dict, List, Optional, Union


class Source(str, Enum):
    
    CNN = "CNN"
    FoxNews = "FoxNews"
    BBC = "BBC"
    Reddit = "Reddit"
    Twitter = "Twitter"
    Facebook = "Facebook"
    Other = "Other"

class Fact(BaseModel):
    
    
    citation: List[str]
    summary: str

class Quote(BaseModel):
    
    
    speaker: str
    content: str

class Response(BaseModel):
    
    
    quotes: List["Quote"]
    facts: List["Fact"]

class Resume(BaseModel):
    
    
    name: str
    email: str
    experience: List[str]
    skills: List[str]
